### ISSUE TITLE
vscode 提示 main.ts import ./App  Cannot find module './App.vue

### ISSUE THREAD

**Issue by fenis** [ws456999/vue-typescript-starter#11]
import * as lodash from 'lodash'
import Vue from 'vue'

declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}

// 全局变量设置
declare global {
  const _: typeof lodash
}

// iview 全局方法
declare module 'vue/types/vue' {
  interface Vue {
    $Message: any,
    $Modal: any
  }
}

**Comment by ws456999** [comment]
@fenis 请问有最小实现吗，可能是依赖的版本变化

**Comment by ws456999** [comment]
@fenis 

```ts
declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}
```

这段代码新起一个文件来单独放置

**Comment by fenis** [comment]
ok, 我尝试看看，虽然我也有建多一个单独放过，不过好像是有问题，vscode这个问题太恶心了
