### ISSUE TITLE
【编译性能】npm run build需要10分钟

### ISSUE THREAD

**Issue by zyqshanshui** [ws456999/vue-typescript-starter#12]
工程刚开始使用的很流畅，后来vue的第三方内容越来越多，vue-router、vuex、axios、vue-i18n、ElementUI、jQuery，并且工程的代码量也逐渐上来之后，编译一次（npm run build）需要10分钟，启动（npm run dev）需要12分钟左右。

想请教大神，有什么建议么，或者定位手段？

**Comment by zyqshanshui** [comment]
已解决，通过ts-loader的设置解决了，具体原理：https://github.com/TypeStrong/ts-loader#loader-options

![image](https://user-images.githubusercontent.com/24558533/45407462-1186cb00-b69c-11e8-8a6e-837472bbe5a0.png)

同时增加插件

![image](https://user-images.githubusercontent.com/24558533/45407528-4004a600-b69c-11e8-81cd-bfbffd1f16b4.png)

**Comment by ws456999** [comment]
@zyqshanshui 好的，谢谢，对我也有用
