### ISSUE TITLE
项目中碰到的问题

### ISSUE THREAD

**Issue by twinkle77** [ws456999/vue-typescript-starter#2]
* .vue文件不支持tslint, 貌似一直是eslint在报错
* 引用第三方无类型声明的库，比如vue-lazyload, 只能通过自己编写x.d.ts文件吗？
* 在父组件里面调用子组件实例上的方法```this.$refs.children.refresh()```是不行的，请问下怎么解决?

typescript新手。请求下博主，万分感谢

**Comment by jkchao** [comment]
@sinner77 
hi
- eslint 好像并不识别 .d.ts 里声明的东西，比如 interface 。
- 确实只能新写 .d.ts 。
- 解决这个有两种方式，(this.$refs[formName] as HTMLFormElement).refresh()，另一种方式是写

```javascript
export default class Hello extends Vue {
  $refs: {
    form: HTMLFormElement
  }
  // ...
}
```
其他问题可以参考下这个项目 

https://github.com/jkchao/vue-admin

**Comment by ws456999** [comment]
@sinner77 ，用 @jkchao 的方式确实是最好的办法
