### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by faelssim** [ws456999/vue-typescript-starter#8]
我把项目拷贝下来，运行报错；啥情况？请赐教，谢谢哈

![tim 20180628215457](https://user-images.githubusercontent.com/17715030/42038612-f443629c-7b1d-11e8-8ea0-c8acd4c179f4.png)

**Comment by ws456999** [comment]
@wk0606 把 `ts-loader` 降到 `4.2.0`

```bash
npm i ts-loader@4.2.0
```

**Comment by ws456999** [comment]
todo:

升级项目依赖

**Comment by ws456999** [comment]
@wk0606 现在直接clone下来就能用了
