### ISSUE TITLE
我用的vue-cli3.0配的ts报找不到文件，你知道吗？

### ISSUE THREAD

**Issue by tcly861204** [ws456999/vue-typescript-starter#9]
`|  Building for production...

 ERROR  Failed to compile with 2 errors                                                                                                                                                                             19:46:20
These relative modules were not found:

* ./router/index in ./src/main.ts
* ./store/index in ./src/main.ts
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuexdemo@0.1.0 build: `vue-cli-service build``

**Comment by ws456999** [comment]
有重现的repo么

**Comment by beiguancyc** [comment]
出现这个问题的原因是vue-shim.d.ts文件
如果import Vue from 'vue'写在了方法外面会有这个问题，写在方法内部全局方法会提示不存在，但是可以正常运行。
如何两全其美，还请作者在完善一下

**Comment by ws456999** [comment]
@beiguancyc 这个问题，我也发现了，我到时候更新一下

**Comment by beiguancyc** [comment]
> @beiguancyc 这个问题，我也发现了，我到时候更新一下

静候佳音
